In [1]:
import matplotlib.pyplot as plt
import numpy as np
import cv2
import os
import PIL
import tensorflow as tf

from tensorflow import keras

In [2]:
from tensorflow.keras import models, layers

In [3]:
tf.__version__

'2.8.3'

In [4]:
#img = 256 x 256
#batch 32 

In [5]:
dataset = tf.keras.preprocessing.image_dataset_from_directory(
    "dataset/PlantDiseasesDataset/train",
    shuffle=True,
    image_size=(256,256),
    batch_size= 32
)

Found 70295 files belonging to 38 classes.


In [6]:
className = dataset.class_names
className

['Apple___Apple_scab',
 'Apple___Black_rot',
 'Apple___Cedar_apple_rust',
 'Apple___healthy',
 'Blueberry___healthy',
 'Cherry_(including_sour)___Powdery_mildew',
 'Cherry_(including_sour)___healthy',
 'Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot',
 'Corn_(maize)___Common_rust_',
 'Corn_(maize)___Northern_Leaf_Blight',
 'Corn_(maize)___healthy',
 'Grape___Black_rot',
 'Grape___Esca_(Black_Measles)',
 'Grape___Leaf_blight_(Isariopsis_Leaf_Spot)',
 'Grape___healthy',
 'Orange___Haunglongbing_(Citrus_greening)',
 'Peach___Bacterial_spot',
 'Peach___healthy',
 'Pepper,_bell___Bacterial_spot',
 'Pepper,_bell___healthy',
 'Potato___Early_blight',
 'Potato___Late_blight',
 'Potato___healthy',
 'Raspberry___healthy',
 'Soybean___healthy',
 'Squash___Powdery_mildew',
 'Strawberry___Leaf_scorch',
 'Strawberry___healthy',
 'Tomato___Bacterial_spot',
 'Tomato___Early_blight',
 'Tomato___Late_blight',
 'Tomato___Leaf_Mold',
 'Tomato___Septoria_leaf_spot',
 'Tomato___Spider_mites Two-spotted_

In [7]:
len(dataset)

2197

In [8]:
for imgBatch, lableBatch in dataset.take(1):
    print(imgBatch.shape)
    print(lableBatch.numpy())

(32, 256, 256, 3)
[ 5  8  7  9 32 14  8  8 19 10 13 31  3  4  6 16 30 22 30 18 29  6  9 33
  5  5 29 29 19  6  4 10]


In [9]:
for imgBatch, lableBatch in dataset.take(1):
    print(imgBatch[0])
    print(imgBatch[0].numpy())
    print(imgBatch[0].shape)

tf.Tensor(
[[[188. 194. 210.]
  [190. 196. 212.]
  [194. 200. 216.]
  ...
  [107. 105. 119.]
  [127. 125. 139.]
  [126. 124. 138.]]

 [[196. 202. 218.]
  [197. 203. 219.]
  [199. 205. 221.]
  ...
  [122. 120. 134.]
  [131. 129. 143.]
  [120. 118. 132.]]

 [[197. 203. 219.]
  [198. 204. 220.]
  [199. 205. 221.]
  ...
  [127. 125. 139.]
  [123. 121. 135.]
  [100.  98. 112.]]

 ...

 [[155. 162. 178.]
  [153. 160. 176.]
  [152. 159. 175.]
  ...
  [123. 125. 137.]
  [121. 123. 135.]
  [142. 144. 156.]]

 [[155. 162. 178.]
  [155. 162. 178.]
  [154. 161. 177.]
  ...
  [137. 139. 151.]
  [129. 131. 143.]
  [147. 149. 161.]]

 [[149. 156. 172.]
  [149. 156. 172.]
  [150. 157. 173.]
  ...
  [143. 145. 157.]
  [127. 129. 141.]
  [139. 141. 153.]]], shape=(256, 256, 3), dtype=float32)
[[[188. 194. 210.]
  [190. 196. 212.]
  [194. 200. 216.]
  ...
  [107. 105. 119.]
  [127. 125. 139.]
  [126. 124. 138.]]

 [[196. 202. 218.]
  [197. 203. 219.]
  [199. 205. 221.]
  ...
  [122. 120. 134.]
  [131. 12

In [10]:
trainDataset = dataset

In [11]:
len(trainDataset)

2197

In [12]:
dataset1 = tf.keras.preprocessing.image_dataset_from_directory(
    "dataset/PlantDiseasesDataset/valid",
    shuffle=True,
    image_size=(256,256),
    batch_size= 32
)

Found 17572 files belonging to 38 classes.


In [13]:
len(dataset1)

550

In [14]:
className1 = dataset1.class_names
className1

['Apple___Apple_scab',
 'Apple___Black_rot',
 'Apple___Cedar_apple_rust',
 'Apple___healthy',
 'Blueberry___healthy',
 'Cherry_(including_sour)___Powdery_mildew',
 'Cherry_(including_sour)___healthy',
 'Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot',
 'Corn_(maize)___Common_rust_',
 'Corn_(maize)___Northern_Leaf_Blight',
 'Corn_(maize)___healthy',
 'Grape___Black_rot',
 'Grape___Esca_(Black_Measles)',
 'Grape___Leaf_blight_(Isariopsis_Leaf_Spot)',
 'Grape___healthy',
 'Orange___Haunglongbing_(Citrus_greening)',
 'Peach___Bacterial_spot',
 'Peach___healthy',
 'Pepper,_bell___Bacterial_spot',
 'Pepper,_bell___healthy',
 'Potato___Early_blight',
 'Potato___Late_blight',
 'Potato___healthy',
 'Raspberry___healthy',
 'Soybean___healthy',
 'Squash___Powdery_mildew',
 'Strawberry___Leaf_scorch',
 'Strawberry___healthy',
 'Tomato___Bacterial_spot',
 'Tomato___Early_blight',
 'Tomato___Late_blight',
 'Tomato___Leaf_Mold',
 'Tomato___Septoria_leaf_spot',
 'Tomato___Spider_mites Two-spotted_

In [15]:
len(dataset1)

550

In [16]:
validDataset = dataset1

In [17]:
dataset2 = tf.keras.preprocessing.image_dataset_from_directory(
    "dataset/test",
    shuffle=True,
    image_size=(256,256),
    batch_size= 32
)

Found 33 files belonging to 1 classes.


In [18]:
len(dataset2)

2

In [19]:
className2 = dataset2.class_names
className2

['test']

In [20]:
len(dataset2)

2

In [21]:
testDataset = dataset2

In [22]:
trainDataset = trainDataset.cache().shuffle(1000).prefetch(buffer_size=tf.data.AUTOTUNE)
validDataset = validDataset.cache().shuffle(1000).prefetch(buffer_size=tf.data.AUTOTUNE)
testDataset = testDataset.cache().shuffle(1000).prefetch(buffer_size=tf.data.AUTOTUNE)

In [23]:
resize_rescale = tf.keras.Sequential([
        
    layers.experimental.preprocessing.Resizing(256,256),
    layers.experimental.preprocessing.Rescaling(1.0/255),   
])

In [24]:
data_augmentation = tf.keras.Sequential([
    layers.experimental.preprocessing.RandomFlip("horizontal_and_vertical"),
    layers.experimental.preprocessing.RandomRotation(0.2),
])

In [27]:
model = models.Sequential([
    resize_rescale,
    data_augmentation,
    
    layers.Conv2D(32,(3,3),activation='relu',input_shape = (32,256, 256, 3)),
    layers.MaxPool2D((2,2)),
    
    layers.Conv2D(64,kernel_size=(3,3),activation='relu'),
    layers.MaxPool2D((2,2)),
    
    layers.Conv2D(64,(3,3),activation='relu'),
    layers.MaxPool2D((2,2)),
    
    layers.Conv2D(64,(3,3),activation='relu'),
    layers.MaxPool2D((2,2)),
    
    layers.Conv2D(64,(3,3),activation='relu'),
    layers.MaxPool2D((2,2)),
    
    layers.Conv2D(64,(3,3),activation='relu'),
    layers.MaxPool2D((2,2)),
    
    layers.Flatten(),
    
    layers.Dense(64,activation='relu'),
    
    layers.Dense(38,activation='softmax'),
])

In [28]:
model.build((32,256, 256, 3))

In [29]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 sequential (Sequential)     (32, 256, 256, 3)         0         
                                                                 
 sequential_1 (Sequential)   (32, 256, 256, 3)         0         
                                                                 
 conv2d_6 (Conv2D)           (32, 254, 254, 32)        896       
                                                                 
 max_pooling2d_6 (MaxPooling  (32, 127, 127, 32)       0         
 2D)                                                             
                                                                 
 conv2d_7 (Conv2D)           (32, 125, 125, 64)        18496     
                                                                 
 max_pooling2d_7 (MaxPooling  (32, 62, 62, 64)         0         
 2D)                                                  